### ISSUE TITLE
need Opacity adjustment

### ISSUE THREAD

**Issue by jor8888** [Taschenbuch/Gw2TinyWvwKillCounter#4]
need Opacity adjustment if possible.

**Comment by Taschenbuch** [comment]
added that to my todo list.

**Comment by Taschenbuch** [comment]
I updated version 3 (alpha). The background opacity can now be changed in the settings window:
https://github.com/Taschenbuch/Gw2TinyWvwKillCounter/releases/tag/version_3_alpha
